%RUN_TC_CRP_SPAN_DEMO Exercise the MTC1 TC/CRP span reference flow.
%
% This script is location-aware. It may be run directly from MATLAB
% without first changing into scripts/matlab/examples.

clear; clc;

% Step 23: Locate the MATLAB support directories and run the MTC1 generator.
this_file = mfilename('fullpath');
examples_dir = fileparts(this_file);
matlab_dir = fileparts(examples_dir);

addpath(fullfile(matlab_dir, 'models'));
addpath(fullfile(matlab_dir, 'generators'));

T = generate_tc_crp_span_vectors();

disp('MTC1 TC/CRP directed cases:');
disp(T);

fprintf('\nMTC1 summary:\n');
fprintf('  rows:               %d\n', height(T));
fprintf('  conceptual cases:   %d\n', numel(unique(T.case_name)));

% Step 24: Assert the generator shape and core TC-span boundary behavior.
assert(height(T) == 13, ...
    'MTC1 demo expected exactly 13 directed rows.');

assert(numel(unique(T.case_name)) == 9, ...
    'MTC1 demo expected exactly 9 conceptual cases.');

first_row = T(T.case_name == "first_in_range_vpn", :);
assert(height(first_row) == 1, ...
    'Expected exactly one first_in_range_vpn row.');
assert(first_row.vpn == 0 && ...
    first_row.in_range && ...
    first_row.descriptor_request && ...
    first_row.descriptor_addr_valid && ...
    first_row.descriptor_addr == first_row.crp, ...
    'First in-range VPN invariant failed.');

last_row = T(T.case_name == "last_in_range_vpn", :);
assert(height(last_row) == 1, ...
    'Expected exactly one last_in_range_vpn row.');
assert(last_row.vpn + uint64(1) == last_row.table_entries && ...
    last_row.in_range && ...
    last_row.descriptor_request && ...
    last_row.descriptor_addr_valid, ...
    'Last in-range VPN invariant failed.');

out_row = T(T.case_name == "first_out_of_range_vpn", :);
assert(height(out_row) == 1, ...
    'Expected exactly one first_out_of_range_vpn row.');
assert(out_row.vpn == out_row.table_entries && ...
    ~out_row.in_range && ...
    ~out_row.descriptor_request && ...
    ~out_row.descriptor_addr_valid && ...
    out_row.descriptor_addr == uint64(0) && ...
    out_row.prewalk_fault == "unmapped_span", ...
    'First out-of-range VPN invariant failed.');

zero_row = T(T.case_name == "zero_table_span", :);
assert(height(zero_row) == 1, ...
    'Expected exactly one zero_table_span row.');
assert(zero_row.vpn == 0 && ...
    zero_row.table_entries == 0 && ...
    ~zero_row.in_range && ...
    ~zero_row.descriptor_request && ...
    zero_row.prewalk_fault == "unmapped_span", ...
    'Zero-span invariant failed.');

fprintf('Step 24 core assertions passed.\n');

% Step 25: Assert the paired MTC1 comparison cases.

crp_rows = T(T.case_name == "alternate_crp", :);
assert(height(crp_rows) == 2, ...
    'Expected exactly two alternate_crp rows.');
assert(crp_rows.va(1) == crp_rows.va(2) && ...
    crp_rows.vpn(1) == crp_rows.vpn(2) && ...
    crp_rows.table_entries(1) == crp_rows.table_entries(2) && ...
    crp_rows.crp(1) ~= crp_rows.crp(2), ...
    'Alternate-CRP setup invariant failed.');
assert(crp_rows.crp(2) - crp_rows.crp(1) == ...
    crp_rows.descriptor_addr(2) - crp_rows.descriptor_addr(1), ...
    'Alternate-CRP descriptor-address delta invariant failed.');

span_rows = T(T.case_name == "tc_span_change", :);
assert(height(span_rows) == 2, ...
    'Expected exactly two tc_span_change rows.');
assert(span_rows.va(1) == span_rows.va(2) && ...
    span_rows.vpn(1) == span_rows.vpn(2) && ...
    span_rows.crp(1) == span_rows.crp(2) && ...
    span_rows.table_entries(1) ~= span_rows.table_entries(2) && ...
    span_rows.in_range(1) && ...
    ~span_rows.in_range(2) && ...
    span_rows.descriptor_request(1) && ...
    ~span_rows.descriptor_request(2), ...
    'TC span-change invariant failed.');

srp_row = T(T.case_name == "srp_inert_supervisor", :);
assert(height(srp_row) == 1, ...
    'Expected exactly one srp_inert_supervisor row.');
assert(srp_row.root_source == "CRP" && ...
    ~srp_row.srp_used && ...
    srp_row.crp ~= srp_row.srp && ...
    srp_row.descriptor_addr == ...
    srp_row.crp + srp_row.vpn * uint64(srp_row.descr_bytes), ...
    'SRP-inert invariant failed.');

offset_rows = T(T.case_name == "same_vpn_different_offset", :);
assert(height(offset_rows) == 2, ...
    'Expected exactly two same_vpn_different_offset rows.');
assert(offset_rows.vpn(1) == offset_rows.vpn(2) && ...
    offset_rows.page_offset(1) ~= offset_rows.page_offset(2) && ...
    offset_rows.descriptor_addr(1) == offset_rows.descriptor_addr(2), ...
    'Same-VPN/different-offset invariant failed.');

tc_rows = T(T.case_name == "tc_upper_bits_inert", :);
assert(height(tc_rows) == 2, ...
    'Expected exactly two tc_upper_bits_inert rows.');
assert(tc_rows.tc(1) ~= tc_rows.tc(2) && ...
    tc_rows.table_entries(1) == tc_rows.table_entries(2) && ...
    tc_rows.in_range(1) == tc_rows.in_range(2) && ...
    tc_rows.descriptor_request(1) == tc_rows.descriptor_request(2) && ...
    tc_rows.descriptor_addr(1) == tc_rows.descriptor_addr(2), ...
    'TC-upper-bits-inert invariant failed.');

fprintf('Step 25 paired assertions passed.\n');
fprintf('All MTC1 demo assertions passed.\n');
