function T = generate_tc_crp_span_vectors()
%GENERATE_TC_CRP_SPAN_VECTORS Build deterministic MTC1 directed cases.
% Step 11: Establish the in-memory directed-case generator entry point.

    % Step 12: Build the first directed case and convert its result to one table row.
    R = mmu_tc_crp_span_reference( ...
        hex2dec('000345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata = table( ...
        "first_in_range_vpn", ...
        "baseline", ...
        'VariableNames', {'case_name', 'variant'});

    T = [metadata struct2table(R)];

    % Step 13: Append the last in-range VPN as the second directed table row.
    R_last = mmu_tc_crp_span_reference( ...
        hex2dec('003345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_last = table( ...
        "last_in_range_vpn", ...
        "baseline", ...
        'VariableNames', {'case_name', 'variant'});

    row_last = [metadata_last struct2table(R_last)];
    T = [T; row_last];

    % Step 14: Append the first out-of-range VPN and verify pre-walk rejection.
    R_out = mmu_tc_crp_span_reference( ...
        hex2dec('004345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_out = table( ...
        "first_out_of_range_vpn", ...
        "baseline", ...
        'VariableNames', {'case_name', 'variant'});

    row_out = [metadata_out struct2table(R_out)];
    T = [T; row_out];

    % Step 15: Compare two CRP bases with the same VA and table span.
    R_crp_a = mmu_tc_crp_span_reference( ...
        hex2dec('002345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_crp_a = table( ...
        "alternate_crp", ...
        "crp_a", ...
        'VariableNames', {'case_name', 'variant'});

    row_crp_a = [metadata_crp_a struct2table(R_crp_a)];

    R_crp_b = mmu_tc_crp_span_reference( ...
        hex2dec('002345'), ...
        1, ...
        hex2dec('003000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_crp_b = table( ...
        "alternate_crp", ...
        "crp_b", ...
        'VariableNames', {'case_name', 'variant'});

    row_crp_b = [metadata_crp_b struct2table(R_crp_b)];

    T = [T; row_crp_a; row_crp_b];

    % Step 16: Compare two TC spans with the same VA and CRP.
    R_span_in = mmu_tc_crp_span_reference( ...
        hex2dec('003345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_span_in = table( ...
        "tc_span_change", ...
        "span_4_in", ...
        'VariableNames', {'case_name', 'variant'});

    row_span_in = [metadata_span_in struct2table(R_span_in)];

    R_span_out = mmu_tc_crp_span_reference( ...
        hex2dec('003345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        3, ...
        struct());

    metadata_span_out = table( ...
        "tc_span_change", ...
        "span_3_out", ...
        'VariableNames', {'case_name', 'variant'});

    row_span_out = [metadata_span_out struct2table(R_span_out)];

    T = [T; row_span_in; row_span_out];

    % Step 17: Show that a supervisor-class FC still uses CRP and leaves SRP inert.
    R_srp = mmu_tc_crp_span_reference( ...
        hex2dec('002345'), ...
        5, ...
        hex2dec('001000'), ...
        hex2dec('00A000'), ...
        4, ...
        struct());

    metadata_srp = table( ...
        "srp_inert_supervisor", ...
        "supervisor_data", ...
        'VariableNames', {'case_name', 'variant'});

    row_srp = [metadata_srp struct2table(R_srp)];
    T = [T; row_srp];

    % Step 18: Compare two VAs with the same VPN but different page offsets.
    R_offset_a = mmu_tc_crp_span_reference( ...
        hex2dec('002123'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_offset_a = table( ...
        "same_vpn_different_offset", ...
        "offset_123", ...
        'VariableNames', {'case_name', 'variant'});

    row_offset_a = [metadata_offset_a struct2table(R_offset_a)];

    R_offset_b = mmu_tc_crp_span_reference( ...
        hex2dec('002ABC'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        4, ...
        struct());

    metadata_offset_b = table( ...
        "same_vpn_different_offset", ...
        "offset_abc", ...
        'VariableNames', {'case_name', 'variant'});

    row_offset_b = [metadata_offset_b struct2table(R_offset_b)];

    T = [T; row_offset_a; row_offset_b];

    % Step 19: Show that a zero TC span rejects even VPN 0 before any request.
    R_zero_span = mmu_tc_crp_span_reference( ...
        hex2dec('000345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        0, ...
        struct());

    metadata_zero_span = table( ...
        "zero_table_span", ...
        "vpn_0_rejected", ...
        'VariableNames', {'case_name', 'variant'});

    row_zero_span = [metadata_zero_span struct2table(R_zero_span)];
    T = [T; row_zero_span];

    % Step 20: Show that TC bits above VPN_WIDTH do not affect the current span.
    R_tc_low = mmu_tc_crp_span_reference( ...
        hex2dec('002345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        hex2dec('000004'), ...
        struct());

    metadata_tc_low = table( ...
        "tc_upper_bits_inert", ...
        "low_bits_only", ...
        'VariableNames', {'case_name', 'variant'});

    row_tc_low = [metadata_tc_low struct2table(R_tc_low)];

    R_tc_upper = mmu_tc_crp_span_reference( ...
        hex2dec('002345'), ...
        1, ...
        hex2dec('001000'), ...
        hex2dec('002000'), ...
        hex2dec('001004'), ...
        struct());

    metadata_tc_upper = table( ...
        "tc_upper_bits_inert", ...
        "upper_bit_set", ...
        'VariableNames', {'case_name', 'variant'});

    row_tc_upper = [metadata_tc_upper struct2table(R_tc_upper)];

    T = [T; row_tc_low; row_tc_upper];

end
